language: java
jdk:
- oraclejdk8
notifications:
  email: false
install:
- 'chmod +x ./gradlew'
script: ./gradlew build --stacktrace --info
after_success:
- 'chmod +x ./continuum.sh'
- './continuum.sh'
